# Generated by Django 4.2.28 on 2026-02-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("disease", "Disease Detection"),
                            ("price", "Price Prediction"),
                            ("soil", "Soil Recommendation"),
                            ("weather", "Weather Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("total_predictions", models.IntegerField(default=0)),
                ("correct_predictions", models.IntegerField(default=0)),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_model_metrics",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="ModelTrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("disease", "Disease Detection"),
                            ("price", "Price Prediction"),
                            ("soil", "Soil Recommendation"),
                            ("weather", "Weather Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("training_start", models.DateTimeField()),
                ("training_end", models.DateTimeField(blank=True, null=True)),
                ("dataset_size", models.IntegerField()),
                ("epochs", models.IntegerField(blank=True, null=True)),
                ("batch_size", models.IntegerField(blank=True, null=True)),
                ("final_loss", models.FloatField(blank=True, null=True)),
                ("final_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "model_training_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("forecast_date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("humidity", models.FloatField()),
                ("rainfall_probability", models.FloatField()),
                ("rainfall_amount", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("weather_condition", models.CharField(max_length=50)),
                ("uv_index", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "weather_forecasts",
                "ordering": ["-forecast_date"],
                "unique_together": {("location", "forecast_date")},
            },
        ),
        migrations.CreateModel(
            name="SoilRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nitrogen", models.FloatField()),
                ("phosphorus", models.FloatField()),
                ("potassium", models.FloatField()),
                ("ph_level", models.FloatField()),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("rainfall", models.FloatField(blank=True, null=True)),
                ("recommended_crop", models.CharField(max_length=100)),
                ("confidence_score", models.FloatField()),
                ("alternative_crops", models.JSONField(blank=True, default=list)),
                ("fertilizer_suggestion", models.TextField()),
                ("soil_health_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "soil_recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="disease_detection/")),
                ("disease_name", models.CharField(max_length=200)),
                ("confidence_score", models.FloatField()),
                ("treatment_suggestion", models.TextField()),
                ("affected_areas", models.JSONField(blank=True, default=list)),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "disease_detection_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CropPricePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=50)),
                ("rainfall", models.FloatField(blank=True, null=True)),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_trend",
                    models.CharField(
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("confidence_interval", models.JSONField(blank=True, default=dict)),
                ("historical_data", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crop_price_predictions",
                "ordering": ["-created_at"],
            },
        ),
    ]
