# Generated by Django 4.2.28 on 2026-02-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("temperature_avg", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField()),
                ("rainfall", models.FloatField(default=0, help_text="Rainfall in mm")),
                ("rainfall_probability", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                (
                    "wind_direction",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("weather_condition", models.CharField(max_length=50)),
                ("uv_index", models.FloatField(blank=True, null=True)),
                ("visibility", models.FloatField(blank=True, null=True)),
                ("sunrise", models.TimeField(blank=True, null=True)),
                ("sunset", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "weather_logs",
                "ordering": ["-date"],
                "unique_together": {("location", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("heavy_rain", "Heavy Rain Warning"),
                            ("drought", "Drought Warning"),
                            ("frost", "Frost Warning"),
                            ("heat_wave", "Heat Wave Warning"),
                            ("storm", "Storm Warning"),
                            ("flood", "Flood Warning"),
                            ("strong_wind", "Strong Wind Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "acknowledged_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weather_alerts",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmerWeatherPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("daily_forecast", models.BooleanField(default=True)),
                ("weather_alerts", models.BooleanField(default=True)),
                ("irrigation_reminders", models.BooleanField(default=True)),
                (
                    "rain_alert_threshold",
                    models.FloatField(
                        default=20, help_text="Rainfall amount in mm to trigger alert"
                    ),
                ),
                (
                    "temp_high_threshold",
                    models.FloatField(
                        default=40, help_text="High temperature threshold in Celsius"
                    ),
                ),
                (
                    "temp_low_threshold",
                    models.FloatField(
                        default=10, help_text="Low temperature threshold in Celsius"
                    ),
                ),
                ("monitored_crops", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farmer_weather_preferences",
            },
        ),
        migrations.CreateModel(
            name="CropWeatherIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("growing_degree_days", models.FloatField(blank=True, null=True)),
                ("heat_stress_index", models.FloatField(blank=True, null=True)),
                ("drought_index", models.FloatField(blank=True, null=True)),
                ("moisture_stress_index", models.FloatField(blank=True, null=True)),
                ("irrigation_recommended", models.BooleanField(default=False)),
                (
                    "irrigation_amount",
                    models.FloatField(
                        blank=True, help_text="Recommended irrigation in mm", null=True
                    ),
                ),
                ("protection_needed", models.BooleanField(default=False)),
                ("protection_measures", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "crop_weather_indices",
                "ordering": ["-date"],
                "unique_together": {("crop", "location", "date")},
            },
        ),
    ]
