# Generated by Django 4.2.28 on 2026-02-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("new_users_today", models.IntegerField(default=0)),
                ("active_farmers", models.IntegerField(default=0)),
                ("active_buyers", models.IntegerField(default=0)),
                ("total_crops_listed", models.IntegerField(default=0)),
                ("crops_sold_today", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                ("orders_today", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "revenue_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_predictions", models.IntegerField(default=0)),
                ("predictions_today", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MarketTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "modal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_arrivals", models.IntegerField(default=0)),
                (
                    "market_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "market_trends",
                "ordering": ["-date"],
                "unique_together": {("crop", "state", "date", "market_name")},
            },
        ),
        migrations.CreateModel(
            name="DailyActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("crop_listed", "Crop Listed"),
                            ("order_placed", "Order Placed"),
                            ("prediction_made", "Prediction Made"),
                            ("disease_detected", "Disease Detected"),
                            ("price_predicted", "Price Predicted"),
                            ("soil_tested", "Soil Tested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("disease", "Disease Detection"),
                            ("price", "Price Prediction"),
                            ("soil", "Soil Recommendation"),
                            ("weather", "Weather Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("total_predictions", models.IntegerField(default=0)),
                ("correct_predictions", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("positive_feedback", models.IntegerField(default=0)),
                ("negative_feedback", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_model_performance",
                "ordering": ["-date"],
                "unique_together": {("model_type", "date")},
            },
        ),
    ]
