# Generated by Django 4.2.28 on 2026-02-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("nitrogen", models.FloatField(help_text="Nitrogen content in kg/ha")),
                (
                    "phosphorus",
                    models.FloatField(help_text="Phosphorus content in kg/ha"),
                ),
                (
                    "potassium",
                    models.FloatField(help_text="Potassium content in kg/ha"),
                ),
                ("ph_level", models.FloatField(help_text="pH level")),
                (
                    "organic_carbon",
                    models.FloatField(
                        blank=True, help_text="Organic carbon %", null=True
                    ),
                ),
                (
                    "electrical_conductivity",
                    models.FloatField(blank=True, help_text="EC in dS/m", null=True),
                ),
                (
                    "zinc",
                    models.FloatField(blank=True, help_text="Zinc in ppm", null=True),
                ),
                (
                    "iron",
                    models.FloatField(blank=True, help_text="Iron in ppm", null=True),
                ),
                (
                    "manganese",
                    models.FloatField(
                        blank=True, help_text="Manganese in ppm", null=True
                    ),
                ),
                (
                    "copper",
                    models.FloatField(blank=True, help_text="Copper in ppm", null=True),
                ),
                (
                    "boron",
                    models.FloatField(blank=True, help_text="Boron in ppm", null=True),
                ),
                (
                    "soil_texture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("sandy_loam", "Sandy Loam"),
                            ("clay_loam", "Clay Loam"),
                            ("silty_loam", "Silty Loam"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("soil_color", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "soil_data",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="SoilTestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="soil_reports/")),
                ("recommendations", models.TextField()),
                ("suitable_crops", models.JSONField(default=list)),
                (
                    "fertility_rating",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "soil_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="soil.soildata",
                    ),
                ),
            ],
            options={
                "db_table": "soil_test_reports",
            },
        ),
        migrations.CreateModel(
            name="FertilizerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("field_location", models.CharField(max_length=255)),
                ("application_date", models.DateField()),
                ("fertilizer_name", models.CharField(max_length=200)),
                (
                    "fertilizer_type",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("inorganic", "Inorganic/Chemical"),
                            ("bio", "Bio-fertilizer"),
                            ("micronutrient", "Micronutrient"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity_applied", models.FloatField(help_text="Quantity in kg")),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("broadcasting", "Broadcasting"),
                            ("banding", "Banding"),
                            ("foliar", "Foliar Spray"),
                            ("fertigation", "Fertigation"),
                            ("top_dressing", "Top Dressing"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("effectiveness_rating", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fertilizer_applications",
                "ordering": ["-application_date"],
            },
        ),
    ]
